### ISSUE TITLE
toggle button does not work on ssl site

### ISSUE THREAD

**Issue by jlecard** [Smile-SA/redmine_smile_togglesidebar#1]
I have a redmine app running in ssl (config.force_ssl in config/environments/development.rb).

When running this app with the plugin enabled, I get this error in js console:

`Blocked loading mixed active content “http://localhost:3000/sidebar/toggle?original_action=index&original_controller=projects”`

and the sidebar is never hidden...

Tested with 
* redmine clone (tag 3.3.1)
* redmine_smile_togglesidebar v1.0.4

System:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Developement environment:
* Web server: 
thin 1.7.0 codename Dunder Mifflin, started with --ssl flag

To reproduce:
* Configure a redmine install from tagged version 3.3.1, on a development environment
* Setup your favorite dev database settings as per redmine's doc
* copy the redmine_smile_togglesidebar in the plugins directory
* Edit your config/environements/development.rb file, add the line in the "configure" block
`config.force_ssl = true`
* Add the following line in the Gemfile of the redmine source directory:
`gem "thin"`
* Run `bundle install` from redmine source directory
* Run `thin start --ssl` redmine source directory
* Navigate to http://localhost:3000 
=> You should be redirected to https://localhost:3000
* Confirm security exception and log to redmine as admin
* Navigate to a page where toggle button is visible (ie [projects](https://localhost:3000/projects))
* Click the toggle button

=> Nothing happens and the error shows in console

**Comment by Utopism** [comment]
Hi jlecard, thanks for this bug report.

Whether to display the url with http or https is determined in the button_toggle_sidebar helper :
                  sidebar_toggle_url(
                    :original_controller => controller_name,
                    :original_action => action_name,
                    :protocol => Setting.protocol
                  ),
Setting.protocol is configured in the Admin :
Administration > Settings > General > Protocol dropdown list

This should do the trick !

**Comment by ennder** [comment]
Hi James, did you managed to fix your issue ?

**Comment by Utopism** [comment]
Closing this issue,

I suppose the proposed solution is ok.
