### ISSUE TITLE
Images to minimize/maximize don't show up

### ISSUE THREAD

**Issue by stefan-1st** [Smile-SA/redmine_smile_togglesidebar#3]
After installing the plugin the images are not visible. The are not copied to the `/plugin_assets/redmine_smile_togglesidebar/images` directory.

We are using redmine v3.4.2 .

**Comment by Utopism** [comment]
Hi, what is you version of Rails / Ruby ?

**Comment by Utopism** [comment]
- TODO : Test with RM v3.4

**Comment by Utopism** [comment]
Hi, do you still have the issue ?
The plugin assets publication is a Redmine standard process.
- Does Rails has write access to **public/plugin_assets** ?
- Do you have an error in your log file about publishing assets ?

**Comment by Utopism** [comment]
Having no feedback on this issue, I am closing it, no way to investigate more.
