### ISSUE TITLE
Error after deploying in redmine 4.0.1

### ISSUE THREAD

**Issue by mverberg** [Smile-SA/redmine_smile_togglesidebar#4]
After installing the plugin in Redmine 4.0.1 on Rails 5.2.2 and Ruby 2.5.3 using Mysql2:

bundle exec rake redmine:plugins:migrate RAILS_ENV=production

rake aborted!
NoMethodError: undefined method `alias_method_chain' for ApplicationHelper:Module
Did you mean?  alias_method
/home/redmine/live/plugins/redmine_smile_togglesidebar/lib/helpers/smile_helpers_application.rb:137:in `block in extended'
/home/redmine/live/plugins/redmine_smile_togglesidebar/lib/helpers/smile_helpers_application.rb:136:in `instance_eval'
/home/redmine/live/plugins/redmine_smile_togglesidebar/lib/helpers/smile_helpers_application.rb:136:in `extended'
/home/redmine/live/plugins/redmine_smile_togglesidebar/init.rb:58:in `extend'
/home/redmine/live/plugins/redmine_smile_togglesidebar/init.rb:58:in `block in <top (required)>'
/home/redmine/live/config/environment.rb:14:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

I found that the alias_method_chain is depreceated and have to be replaced.

I really like to use your plugin, can you fix the bug?

with kind regards,
Marcel

**Comment by Utopism** [comment]
Hello Marcel,

See my last commit that fixes this issue.
I'm glad you like this plugin :-)
