### ISSUE TITLE
Togglebutton not working

### ISSUE THREAD

**Issue by mverberg** [Smile-SA/redmine_smile_togglesidebar#5]
Hi,

I used your master branche to install your plugin into my redmine 4.0.1
The installation was succesful, but the togglebutton does not work,
nothing happens when I click the button, the sidebar still remains,
see the attachment.
![toggle button not working](https://user-images.githubusercontent.com/394566/53179568-3c366180-35f4-11e9-9009-d18002efab39.png)

**Comment by Utopism** [comment]
Hi,

Can you open the console and see if there is a javascript error ?

**Comment by mverberg** [comment]
Do you mean the production.log?

**Comment by Utopism** [comment]
No I mean the Browser console, that you can find in your browser (Ctrl-Shift-i in Chrome or FF)

**Comment by mverberg** [comment]
The error below occurs when using the toggle button:

jquery-1.11.1-ui-1.11.0-ujs-4.3.1.js?1547967497:4 Mixed Content: The page at 'https://project2.vermeulen-trappen.nl/issues/gantt' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://project2.vermeulen-trappen.nl/sidebar/toggle?original_action=show&original_controller=gantts'. This request has been blocked; the content must be served over HTTPS.

**Comment by mverberg** [comment]
I found the problem: Administration > Settings > General > Protocol. I switched it to HTTPS, now it works! Thanks for the feedback, its really a nice plugin!

**Comment by Utopism** [comment]
I'm glad you fixed the bug.
You're welcome :-)
