### ISSUE TITLE
Cannot run in 4.1.0 redmine

### ISSUE THREAD

**Issue by CNPF** [Smile-SA/redmine_smile_togglesidebar#6]
with redmine 4.1.0 stable encount following problem. Click of bottom doesn't work. No have probleme of install and no message in log
Thanks

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_issue_dynamic_edit     0.6.9
  redmine_issues_tree            0.0.13
  redmine_project_themes         0.0.1
  redmine_smile_togglesidebar    1.0.6

**Comment by Utopism** [comment]
Hi, I just tested on Redmine V4.1, with no problem.

What is your issue exactly ?

**Comment by CNPF** [comment]
Sorry 
http://35.180.27.5/redmine/projects
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://..../redmine/sidebar/toggle?original_action=index&original_controller=projects. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
My redmine have https config. I tested with http.

**Comment by Utopism** [comment]
Great.

If you are happy with this plugin, can you rate it here : http://www.redmine.org/plugins/redmine_smile_togglesidebar

Thanks.
